/**
 * ZIP bundle — assembles all year-end export files into a single ZIP.
 *
 * Uses jszip. Returns a Buffer containing the ZIP bytes.
 */

import JSZip from "jszip";
import type { EurYearResult } from "$lib/server/domain/eur.js";
import type { SpendenlisteRow } from "./spendenliste-csv.js";
import type { BelegIndexRow } from "./beleg-index.js";
import { generateAnlageGemCsv } from "./anlage-gem-csv.js";
import { generateSpendenliste } from "./spendenliste-csv.js";
import { generateBelegIndex } from "./beleg-index.js";
import { generateGobdZ3Xml, generateGobdReadme } from "./gobd-z3.js";
import type { GobdExportInput } from "./gobd-z3.js";

/**
 * C1-M3 — One Bescheinigung-PDF attachment per donation that has one.
 * `bytes` = the PDF rendered/uploaded earlier (we just stream it back).
 */
export interface BescheinigungAttachment {
  filename: string;
  bytes: Uint8Array;
}

/**
 * C1-M3 — Audit-log slice for the bundle. Plain rows; we serialize to CSV.
 * Generated by the bundle caller via a SELECT * FROM audit_log
 * WHERE occurred_at BETWEEN year-start AND year-end (Europe/Berlin).
 */
export interface AuditLogSliceRow {
  occurredAt: string;
  actorKind: string;
  actorDisplay: string;
  action: string;
  entityKind: string;
  entityBusinessId: string | null;
  payload: string;
}

/**
 * C1-M3 — Mitgliedsbeitrags row for the bundle CSV (paid Beiträge only).
 */
export interface MemberBeitragRow {
  memberName: string;
  year: number;
  betragCents: bigint;
  paidCents: bigint;
  gezahltAm: string | null;
}

/**
 * Phase 9 Task 18 — One Beleg file (PDF/image) to embed under
 * `09_Belege-{year}/`. `bundlePath` is the in-bundle relative path
 * (e.g. `expenses/ideeller/A-2026-0001-bueromaterial.pdf`); the route
 * computes it from the source row's ownerKind, sphere, business_id,
 * and (slugified) bezeichnung.
 */
export interface BelegAttachment {
  bundlePath: string;
  bytes: Uint8Array;
}

export interface BundleInput {
  year: number;
  eur: EurYearResult;
  eurPdfBytes: Uint8Array | null;
  spenden: SpendenlisteRow[];
  belege: BelegIndexRow[];
  vereinName: string;
  vereinSteuernummer?: string;
  includeGobdZ3?: boolean;
  /** C1-M3 — Bescheinigung PDFs (already rendered) to bundle in 06_Bescheinigungen/. */
  bescheinigungPdfs?: BescheinigungAttachment[];
  /** C1-M3 — Audit-log slice for the year. */
  auditLogSlice?: AuditLogSliceRow[];
  /** C1-M3 — Paid member-beitrags for the year. */
  memberBeitrags?: MemberBeitragRow[];
  /**
   * Phase 9 Task 18 — Beleg files to embed under `09_Belege-{year}/` in a
   * sphere-aware folder layout. Each attachment carries the in-bundle path
   * and the raw bytes (fetched by the route from FileStorage).
   */
  belegAttachments?: BelegAttachment[];
}

/**
 * Assemble the Jahresabschluss ZIP bundle.
 * File structure:
 *   01_EÜR-{year}.pdf                    — EÜR summary PDF
 *   02_Anlage-Gem-{year}.csv             — Anlage Gem aggregation
 *   03_Spendenliste-{year}.csv           — BMF-required Spendenliste
 *   04_Beleg-Index-{year}.csv            — Beleg index with Drive links
 *   05_GoBD-Z3-{year}/                   — GoBD-Z3 IDEA-XML + README (optional)
 *     gobd_z3_{year}.xml
 *     README.md
 */
export async function buildJahresabschlussBundle(
  input: BundleInput,
): Promise<Buffer> {
  const {
    year,
    eur,
    eurPdfBytes,
    spenden,
    belege,
    vereinName,
    vereinSteuernummer,
  } = input;

  const zip = new JSZip();

  // 01 — EÜR PDF
  if (eurPdfBytes && eurPdfBytes.length > 0) {
    zip.file(`01_EÜR-${year}.pdf`, eurPdfBytes);
  }

  // 02 — Anlage Gem CSV
  const anlageGemCsv = generateAnlageGemCsv(eur);
  zip.file(`02_Anlage-Gem-${year}.csv`, anlageGemCsv);

  // 03 — Spendenliste CSV
  const spendenliste = generateSpendenliste(spenden);
  zip.file(`03_Spendenliste-${year}.csv`, spendenliste);

  // 04 — Beleg-Index CSV
  const belegIndex = generateBelegIndex(belege);
  zip.file(`04_Beleg-Index-${year}.csv`, belegIndex);

  // 05 — GoBD-Z3 IDEA-XML (optional)
  if (input.includeGobdZ3 !== false) {
    const gobdInput: GobdExportInput = {
      year,
      vereinName,
      vereinSteuernummer,
      exportedAt: new Date(),
      einnahmen: [
        ...eur.bySphere.ideeller.einnahmen,
        ...eur.bySphere.vermoegen.einnahmen,
        ...eur.bySphere.zweckbetrieb.einnahmen,
        ...eur.bySphere.wirtschaftlich.einnahmen,
      ],
      ausgaben: [
        ...eur.bySphere.ideeller.ausgaben,
        ...eur.bySphere.vermoegen.ausgaben,
        ...eur.bySphere.zweckbetrieb.ausgaben,
        ...eur.bySphere.wirtschaftlich.ausgaben,
      ],
      spenden,
    };
    const gobdXml = generateGobdZ3Xml(gobdInput);
    const gobdReadme = generateGobdReadme({ year, vereinName });
    const gobdFolder = zip.folder(`05_GoBD-Z3-${year}`);
    gobdFolder?.file(`gobd_z3_${year}.xml`, gobdXml);
    gobdFolder?.file("README.md", gobdReadme);
  }

  // 06 — Bescheinigung PDFs (C1-M3). One subfolder per year, one PDF per
  // donation with an issued Bescheinigung.
  if (input.bescheinigungPdfs && input.bescheinigungPdfs.length > 0) {
    const folder = zip.folder(`06_Bescheinigungen-${year}`);
    for (const att of input.bescheinigungPdfs) {
      folder?.file(att.filename, att.bytes);
    }
  }

  // 07 — Audit-log slice (C1-M3). Includes all rows whose occurred_at falls
  // inside the fiscal year.
  if (input.auditLogSlice && input.auditLogSlice.length > 0) {
    const auditCsv = generateAuditLogCsv(input.auditLogSlice);
    zip.file(`07_Audit-Log-${year}.csv`, auditCsv);
  }

  // 08 — Mitgliedsbeitrags CSV (C1-M3).
  if (input.memberBeitrags && input.memberBeitrags.length > 0) {
    const beitragsCsv = generateMemberBeitragsCsv(input.memberBeitrags);
    zip.file(`08_Mitgliedsbeitraege-${year}.csv`, beitragsCsv);
  }

  // 09 — Beleg files (Phase 9 Task 18). Sphere-aware folder layout under
  // `09_Belege-{year}/`. Each attachment's `bundlePath` is a pre-computed
  // relative path (e.g. `expenses/ideeller/A-2026-0001-slug.pdf`); the
  // route is responsible for slug normalization + sphere bucketing.
  if (input.belegAttachments && input.belegAttachments.length > 0) {
    const folder = zip.folder(`09_Belege-${year}`);
    for (const att of input.belegAttachments) {
      folder?.file(att.bundlePath, att.bytes);
    }
  }

  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
  });
  return buffer;
}

// ── CSV helpers for the new bundle slices ────────────────────────────────────

function csvCell(value: string | number | bigint | null | undefined): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  if (/[;"\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function csvRow(
  cells: Array<string | number | bigint | null | undefined>,
): string {
  return cells.map(csvCell).join(";");
}

export function generateAuditLogCsv(rows: AuditLogSliceRow[]): string {
  const lines: string[] = [];
  // BOM for Excel DE-locale auto-detect
  lines.push(
    "﻿" +
      csvRow([
        "Zeit",
        "Akteur-Art",
        "Akteur",
        "Aktion",
        "Entität (Typ)",
        "Entität (Business-Id)",
        "Payload",
      ]),
  );
  for (const r of rows) {
    lines.push(
      csvRow([
        r.occurredAt,
        r.actorKind,
        r.actorDisplay,
        r.action,
        r.entityKind,
        r.entityBusinessId,
        r.payload,
      ]),
    );
  }
  return lines.join("\r\n") + "\r\n";
}

export function generateMemberBeitragsCsv(rows: MemberBeitragRow[]): string {
  const lines: string[] = [];
  lines.push(
    "﻿" +
      csvRow([
        "Mitglied",
        "Jahr",
        "Soll (EUR)",
        "Bezahlt (EUR)",
        "Soll (Cent)",
        "Bezahlt (Cent)",
        "Gezahlt am",
      ]),
  );
  const eur = (c: bigint) => (Number(c) / 100).toFixed(2).replace(".", ",");
  for (const r of rows) {
    lines.push(
      csvRow([
        r.memberName,
        r.year,
        eur(r.betragCents),
        eur(r.paidCents),
        String(r.betragCents),
        String(r.paidCents),
        r.gezahltAm ?? "",
      ]),
    );
  }
  return lines.join("\r\n") + "\r\n";
}
