// This file intentionally left empty.
// Service worker is generated by @vite-pwa/sveltekit (generateSW strategy)
// via the SvelteKitPWA plugin in vite.config.ts.
// SvelteKit detects this file's presence; keeping it empty prevents
// the framework's own SW registration from conflicting with vite-pwa's output.
export {};
